const routes = require("express").Router();
const users = require("./routes/users");
const friend = require("./routes/friend");
const chat = require("./routes/chat");
const profile = require("./routes/profile");
const collection = require("./routes/collection");
routes.use("/users", users);
routes.use("/friend", friend);
routes.use("/chat", chat);
routes.use("/profile", profile);
routes.use("/collection", collection);
module.exports = routes;
